name: shared_shopping_list
description: "Shared Shopping List is a mobile application that supports group users in managing shopping lists and sharing expenses in a transparent and easy way. The application helps subjects such as households, groups of friends, housemates... organize reasonable spending, reduce financial disputes and enhance cooperation."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
